services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432 

    environment:
      - POSTGRES_DB=jamsow
      - POSTGRES_USER=khadija
      - POSTGRES_PASSWORD=jamsow008kdawan

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080